version: '3'
services:
  npm:
    entrypoint: npm
    image: lambci/lambda:build-nodejs8.10
    volumes:
    - ./:/var/task

  # Build project dependencies
  build:
    command: >-
      sh -c "
        (cd events && npm install --production) &&
        (cd invite && npm install --production) &&
        (cd mods && npm install --production) &&
        (cd welcome && npm install --production)
      "
    image: lambci/lambda:build-nodejs8.10
    volumes:
    - ./:/var/task

  # Deploy to AWS
  terraform:
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_PROFILE:
      TF_VAR_release:
      TF_VAR_repo:
    image: hashicorp/terraform
    volumes:
      - ~/.aws:/root/.aws
      - ./:/terraform
    working_dir: /terraform
