version: '3'
services:

  # Build project dependencies
  build:
    command: >-
      sh -c "
        (cd events && npm install --production) &&
        (cd mods && npm install --production)
      "
    image: lambci/lambda:build-nodejs8.10
    volumes:
    - ./:/var/task

  # Deploy to AWS
  terraform:
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
    image: hashicorp/terraform
    volumes:
      - ~/.aws:/root/.aws
      - ./:/socialismbot
    working_dir: /socialismbot
