version: '3'
services:
  package_events:
    command: >-
      sh -c "
        rm -rf node_modules &&
        npm install --production &&
        zip -r package.zip node_modules/ index.js package.json package-lock.json
      "
    image: lambci/lambda:build-nodejs8.10
    volumes:
    - ./events:/var/task
  package_mods:
    command: >-
      sh -c "
        rm -rf node_modules &&
        npm install --production &&
        zip -r package.zip node_modules/ index.js package.json package-lock.json
      "
    image: lambci/lambda:build-nodejs8.10
    volumes:
    - ./mods:/var/task
